import pygame
import pyautogui

ANCHO_PANTALLA, ALTO_PANTALLA = pyautogui.size()

# ANCHO_PANTALLA = 1200
# ALTO_PANTALLA = 885

ANCHO_PERSONAJE = 100
ALTO_PERSONAJE = 50
ANCHO_MUNICION = 50
ALTO_MUNICION = 20

ALTURA_MENU_SUPERIOR = 80

VELOCIDAD_PERSONAJE = 7
VELOCIDAD_ENEMIGO = 3
VIDAS_PERSONAJE = 3
MUNICION_PERSONAJE = 15

TIEMPO_NIVEL_UNO = 60
CANTIDAD_MISILES_NIVEL_UN0 = 10
CANTIDAD_BALAS_EXTRA_NIVEL_UNO = 3

PANTALLA_JUEGO = pygame.display.set_mode((ANCHO_PANTALLA, ALTO_PANTALLA))
RECURSOS = "Imagenes\\"


