import pygame

ANCHO_PANTALLA = 1200
ALTO_PANTALLA = 885

ANCHO_PERSONAJE = 100
ALTO_PERSONAJE = 50
ANCHO_MUNICION = 50
ALTO_MUNICION = 20

VELOCIDAD_PERSONJE = 8
VELOCIDAD_ENEMIGO = 4
VIDAS_PERSONAJE = 3

PANTALLA_JUEGO = pygame.display.set_mode((ANCHO_PANTALLA, ALTO_PANTALLA))
RECURSOS = "Imagenes\\"


